/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mu_verdigris_splatoid_Splatoid */

#ifndef _Included_mu_verdigris_splatoid_Splatoid
#define _Included_mu_verdigris_splatoid_Splatoid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mu_verdigris_splatoid_Splatoid
 * Method:    nativeTest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mu_verdigris_splatoid_Splatoid_nativeTest
  (JNIEnv *, jobject);

/*
 * Class:     mu_verdigris_splatoid_Splatoid
 * Method:    pythonTest
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_mu_verdigris_splatoid_Splatoid_pythonTest
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
